In [44]:
import pandas as pd
import json

In [45]:
json_data = '''{
 "Header": {
  "Time": "2024-06-06T05:20:45-07:00",
  "ReportName": "CashFlow",
  "DateMacro": "this calendar year-to-date",
  "StartPeriod": "2024-01-01",
  "EndPeriod": "2024-06-06",
  "SummarizeColumnsBy": "Week",
  "Currency": "CAD",
  "Option": [
   {
    "Name": "NoReportData",
    "Value": "false"
   }
  ]
 },
 "Columns": {
  "Column": [
   {
    "ColTitle": "",
    "ColType": "Account"
   },
   {
    "ColTitle": "Jan. 1-6, 2024",
    "ColType": "Money",
    "MetaData": [
     {
      "Name": "StartDate",
      "Value": "2024-01-01"
     },
     {
      "Name": "EndDate",
      "Value": "2024-01-06"
     },
     {
      "Name": "ColKey",
      "Value": "Jan. 1-6, 2024"
     }
    ]
   },
   {
    "ColTitle": "Jan. 7-13, 2024",
    "ColType": "Money",
    "MetaData": [
     {
      "Name": "StartDate",
      "Value": "2024-01-07"
     },
     {
      "Name": "EndDate",
      "Value": "2024-01-13"
     },
     {
      "Name": "ColKey",
      "Value": "Jan. 7-13, 2024"
     }
    ]
   },
   {
    "ColTitle": "Jan. 14-20, 2024",
    "ColType": "Money",
    "MetaData": [
     {
      "Name": "StartDate",
      "Value": "2024-01-14"
     },
     {
      "Name": "EndDate",
      "Value": "2024-01-20"
     },
     {
      "Name": "ColKey",
      "Value": "Jan. 14-20, 2024"
     }
    ]
   },
   {
    "ColTitle": "Jan. 21-27, 2024",
    "ColType": "Money",
    "MetaData": [
     {
      "Name": "StartDate",
      "Value": "2024-01-21"
     },
     {
      "Name": "EndDate",
      "Value": "2024-01-27"
     },
     {
      "Name": "ColKey",
      "Value": "Jan. 21-27, 2024"
     }
    ]
   },
   {
    "ColTitle": "Jan. 28 - Feb. 3, 2024",
    "ColType": "Money",
    "MetaData": [
     {
      "Name": "StartDate",
      "Value": "2024-01-28"
     },
     {
      "Name": "EndDate",
      "Value": "2024-02-03"
     },
     {
      "Name": "ColKey",
      "Value": "Jan. 28 - Feb. 3, 2024"
     }
    ]
   },
   {
    "ColTitle": "Feb. 4-10, 2024",
    "ColType": "Money",
    "MetaData": [
     {
      "Name": "StartDate",
      "Value": "2024-02-04"
     },
     {
      "Name": "EndDate",
      "Value": "2024-02-10"
     },
     {
      "Name": "ColKey",
      "Value": "Feb. 4-10, 2024"
     }
    ]
   },
   {
    "ColTitle": "Feb. 11-17, 2024",
    "ColType": "Money",
    "MetaData": [
     {
      "Name": "StartDate",
      "Value": "2024-02-11"
     },
     {
      "Name": "EndDate",
      "Value": "2024-02-17"
     },
     {
      "Name": "ColKey",
      "Value": "Feb. 11-17, 2024"
     }
    ]
   },
   {
    "ColTitle": "Feb. 18-24, 2024",
    "ColType": "Money",
    "MetaData": [
     {
      "Name": "StartDate",
      "Value": "2024-02-18"
     },
     {
      "Name": "EndDate",
      "Value": "2024-02-24"
     },
     {
      "Name": "ColKey",
      "Value": "Feb. 18-24, 2024"
     }
    ]
   },
   {
    "ColTitle": "Feb. 25 - Mar. 2, 2024",
    "ColType": "Money",
    "MetaData": [
     {
      "Name": "StartDate",
      "Value": "2024-02-25"
     },
     {
      "Name": "EndDate",
      "Value": "2024-03-02"
     },
     {
      "Name": "ColKey",
      "Value": "Feb. 25 - Mar. 2, 2024"
     }
    ]
   },
   {
    "ColTitle": "Mar. 3-9, 2024",
    "ColType": "Money",
    "MetaData": [
     {
      "Name": "StartDate",
      "Value": "2024-03-03"
     },
     {
      "Name": "EndDate",
      "Value": "2024-03-09"
     },
     {
      "Name": "ColKey",
      "Value": "Mar. 3-9, 2024"
     }
    ]
   },
   {
    "ColTitle": "Mar. 10-16, 2024",
    "ColType": "Money",
    "MetaData": [
     {
      "Name": "StartDate",
      "Value": "2024-03-10"
     },
     {
      "Name": "EndDate",
      "Value": "2024-03-16"
     },
     {
      "Name": "ColKey",
      "Value": "Mar. 10-16, 2024"
     }
    ]
   },
   {
    "ColTitle": "Mar. 17-23, 2024",
    "ColType": "Money",
    "MetaData": [
     {
      "Name": "StartDate",
      "Value": "2024-03-17"
     },
     {
      "Name": "EndDate",
      "Value": "2024-03-23"
     },
     {
      "Name": "ColKey",
      "Value": "Mar. 17-23, 2024"
     }
    ]
   },
   {
    "ColTitle": "Mar. 24-30, 2024",
    "ColType": "Money",
    "MetaData": [
     {
      "Name": "StartDate",
      "Value": "2024-03-24"
     },
     {
      "Name": "EndDate",
      "Value": "2024-03-30"
     },
     {
      "Name": "ColKey",
      "Value": "Mar. 24-30, 2024"
     }
    ]
   },
   {
    "ColTitle": "Mar. 31 - Apr. 6, 2024",
    "ColType": "Money",
    "MetaData": [
     {
      "Name": "StartDate",
      "Value": "2024-03-31"
     },
     {
      "Name": "EndDate",
      "Value": "2024-04-06"
     },
     {
      "Name": "ColKey",
      "Value": "Mar. 31 - Apr. 6, 2024"
     }
    ]
   },
   {
    "ColTitle": "Apr. 7-13, 2024",
    "ColType": "Money",
    "MetaData": [
     {
      "Name": "StartDate",
      "Value": "2024-04-07"
     },
     {
      "Name": "EndDate",
      "Value": "2024-04-13"
     },
     {
      "Name": "ColKey",
      "Value": "Apr. 7-13, 2024"
     }
    ]
   },
   {
    "ColTitle": "Apr. 14-20, 2024",
    "ColType": "Money",
    "MetaData": [
     {
      "Name": "StartDate",
      "Value": "2024-04-14"
     },
     {
      "Name": "EndDate",
      "Value": "2024-04-20"
     },
     {
      "Name": "ColKey",
      "Value": "Apr. 14-20, 2024"
     }
    ]
   },
   {
    "ColTitle": "Apr. 21-27, 2024",
    "ColType": "Money",
    "MetaData": [
     {
      "Name": "StartDate",
      "Value": "2024-04-21"
     },
     {
      "Name": "EndDate",
      "Value": "2024-04-27"
     },
     {
      "Name": "ColKey",
      "Value": "Apr. 21-27, 2024"
     }
    ]
   },
   {
    "ColTitle": "Apr. 28 - May 4, 2024",
    "ColType": "Money",
    "MetaData": [
     {
      "Name": "StartDate",
      "Value": "2024-04-28"
     },
     {
      "Name": "EndDate",
      "Value": "2024-05-04"
     },
     {
      "Name": "ColKey",
      "Value": "Apr. 28 - May 4, 2024"
     }
    ]
   },
   {
    "ColTitle": "May 5-11, 2024",
    "ColType": "Money",
    "MetaData": [
     {
      "Name": "StartDate",
      "Value": "2024-05-05"
     },
     {
      "Name": "EndDate",
      "Value": "2024-05-11"
     },
     {
      "Name": "ColKey",
      "Value": "May 5-11, 2024"
     }
    ]
   },
   {
    "ColTitle": "May 12-18, 2024",
    "ColType": "Money",
    "MetaData": [
     {
      "Name": "StartDate",
      "Value": "2024-05-12"
     },
     {
      "Name": "EndDate",
      "Value": "2024-05-18"
     },
     {
      "Name": "ColKey",
      "Value": "May 12-18, 2024"
     }
    ]
   },
   {
    "ColTitle": "May 19-25, 2024",
    "ColType": "Money",
    "MetaData": [
     {
      "Name": "StartDate",
      "Value": "2024-05-19"
     },
     {
      "Name": "EndDate",
      "Value": "2024-05-25"
     },
     {
      "Name": "ColKey",
      "Value": "May 19-25, 2024"
     }
    ]
   },
   {
    "ColTitle": "May 26 - Jun. 1, 2024",
    "ColType": "Money",
    "MetaData": [
     {
      "Name": "StartDate",
      "Value": "2024-05-26"
     },
     {
      "Name": "EndDate",
      "Value": "2024-06-01"
     },
     {
      "Name": "ColKey",
      "Value": "May 26 - Jun. 1, 2024"
     }
    ]
   },
   {
    "ColTitle": "Jun. 2-6, 2024",
    "ColType": "Money",
    "MetaData": [
     {
      "Name": "StartDate",
      "Value": "2024-06-02"
     },
     {
      "Name": "EndDate",
      "Value": "2024-06-06"
     },
     {
      "Name": "ColKey",
      "Value": "Jun. 2-6, 2024"
     }
    ]
   },
   {
    "ColTitle": "Total",
    "ColType": "Money",
    "MetaData": [
     {
      "Name": "ColKey",
      "Value": "total"
     }
    ]
   }
  ]
 },
 "Rows": {
  "Row": [
   {
    "Header": {
     "ColData": [
      {
       "value": "OPERATING ACTIVITIES"
      },
      {
       "value": ""
      },
      {
       "value": ""
      },
      {
       "value": ""
      },
      {
       "value": ""
      },
      {
       "value": ""
      },
      {
       "value": ""
      },
      {
       "value": ""
      },
      {
       "value": ""
      },
      {
       "value": ""
      },
      {
       "value": ""
      },
      {
       "value": ""
      },
      {
       "value": ""
      },
      {
       "value": ""
      },
      {
       "value": ""
      },
      {
       "value": ""
      },
      {
       "value": ""
      },
      {
       "value": ""
      },
      {
       "value": ""
      },
      {
       "value": ""
      },
      {
       "value": ""
      },
      {
       "value": ""
      },
      {
       "value": ""
      },
      {
       "value": ""
      },
      {
       "value": ""
      }
     ]
    },
    "Rows": {
     "Row": [
      {
       "ColData": [
        {
         "value": "Net Income"
        },
        {
         "value": "-33.33"
        },
        {
         "value": "-1549.79"
        },
        {
         "value": "-95.00"
        },
        {
         "value": "-1368.75"
        },
        {
         "value": "3502.48"
        },
        {
         "value": "-1562.32"
        },
        {
         "value": "3453.26"
        },
        {
         "value": "-200.00"
        },
        {
         "value": ""
        },
        {
         "value": "-2220.83"
        },
        {
         "value": "-395.49"
        },
        {
         "value": "-2371.99"
        },
        {
         "value": "-11031.90"
        },
        {
         "value": "-33.33"
        },
        {
         "value": ""
        },
        {
         "value": ""
        },
        {
         "value": "-1632.37"
        },
        {
         "value": "3118.96"
        },
        {
         "value": ""
        },
        {
         "value": ""
        },
        {
         "value": ""
        },
        {
         "value": ""
        },
        {
         "value": ""
        },
        {
         "value": "-12420.40"
        }
       ],
       "type": "Data",
       "group": "NetIncome"
      },
      {
       "Header": {
        "ColData": [
         {
          "value": "Adjustments to reconcile Net Income to Net Cash provided by operations:"
         },
         {
          "value": ""
         },
         {
          "value": ""
         },
         {
          "value": ""
         },
         {
          "value": ""
         },
         {
          "value": ""
         },
         {
          "value": ""
         },
         {
          "value": ""
         },
         {
          "value": ""
         },
         {
          "value": ""
         },
         {
          "value": ""
         },
         {
          "value": ""
         },
         {
          "value": ""
         },
         {
          "value": ""
         },
         {
          "value": ""
         },
         {
          "value": ""
         },
         {
          "value": ""
         },
         {
          "value": ""
         },
         {
          "value": ""
         },
         {
          "value": ""
         },
         {
          "value": ""
         },
         {
          "value": ""
         },
         {
          "value": ""
         },
         {
          "value": ""
         },
         {
          "value": "0.00"
         }
        ]
       },
       "Rows": {
        "Row": [
         {
          "ColData": [
           {
            "value": "Accounts Receivable",
            "id": "32"
           },
           {
            "value": "10226.28"
           },
           {
            "value": ""
           },
           {
            "value": ""
           },
           {
            "value": ""
           },
           {
            "value": "-8441.10"
           },
           {
            "value": ""
           },
           {
            "value": "-8249.00"
           },
           {
            "value": "9415.73"
           },
           {
            "value": ""
           },
           {
            "value": ""
           },
           {
            "value": "-2147.00"
           },
           {
            "value": ""
           },
           {
            "value": "-9435.50"
           },
           {
            "value": ""
           },
           {
            "value": ""
           },
           {
            "value": "1356.00"
           },
           {
            "value": ""
           },
           {
            "value": "-1356.00"
           },
           {
            "value": ""
           },
           {
            "value": ""
           },
           {
            "value": ""
           },
           {
            "value": ""
           },
           {
            "value": ""
           },
           {
            "value": "-8630.59"
           }
          ],
          "type": "Data"
         },
         {
          "ColData": [
           {
            "value": "Inventory Asset",
            "id": "85"
           },
           {
            "value": ""
           },
           {
            "value": ""
           },
           {
            "value": ""
           },
           {
            "value": ""
           },
           {
            "value": ""
           },
           {
            "value": ""
           },
           {
            "value": "3301.74"
           },
           {
            "value": ""
           },
           {
            "value": ""
           },
           {
            "value": ""
           },
           {
            "value": "750.00"
           },
           {
            "value": ""
           },
           {
            "value": "-5804.34"
           },
           {
            "value": ""
           },
           {
            "value": ""
           },
           {
            "value": ""
           },
           {
            "value": ""
           },
           {
            "value": "1981.04"
           },
           {
            "value": ""
           },
           {
            "value": ""
           },
           {
            "value": ""
           },
           {
            "value": ""
           },
           {
            "value": ""
           },
           {
            "value": "228.44"
           }
          ],
          "type": "Data"
         },
         {
          "ColData": [
           {
            "value": "Accumulated Depreciation",
            "id": "33"
           },
           {
            "value": "33.33"
           },
           {
            "value": ""
           },
           {
            "value": ""
           },
           {
            "value": ""
           },
           {
            "value": ""
           },
           {
            "value": "33.33"
           },
           {
            "value": ""
           },
           {
            "value": ""
           },
           {
            "value": ""
           },
           {
            "value": "33.33"
           },
           {
            "value": ""
           },
           {
            "value": ""
           },
           {
            "value": ""
           },
           {
            "value": "33.33"
           },
           {
            "value": ""
           },
           {
            "value": ""
           },
           {
            "value": ""
           },
           {
            "value": ""
           },
           {
            "value": ""
           },
           {
            "value": ""
           },
           {
            "value": ""
           },
           {
            "value": ""
           },
           {
            "value": ""
           },
           {
            "value": "133.32"
           }
          ],
          "type": "Data"
         },
         {
          "ColData": [
           {
            "value": "Accounts Payable",
            "id": "31"
           },
           {
            "value": ""
           },
           {
            "value": ""
           },
           {
            "value": ""
           },
           {
            "value": ""
           },
           {
            "value": ""
           },
           {
            "value": ""
           },
           {
            "value": "508.51"
           },
           {
            "value": "226.00"
           },
           {
            "value": ""
           },
           {
            "value": ""
           },
           {
            "value": ""
           },
           {
            "value": ""
           },
           {
            "value": ""
           },
           {
            "value": ""
           },
           {
            "value": ""
           },
           {
            "value": ""
           },
           {
            "value": ""
           },
           {
            "value": ""
           },
           {
            "value": ""
           },
           {
            "value": ""
           },
           {
            "value": ""
           },
           {
            "value": ""
           },
           {
            "value": ""
           },
           {
            "value": "734.51"
           }
          ],
          "type": "Data"
         },
         {
          "ColData": [
           {
            "value": "Visa Credit Card",
            "id": "79"
           },
           {
            "value": ""
           },
           {
            "value": ""
           },
           {
            "value": ""
           },
           {
            "value": "-1000.00"
           },
           {
            "value": "245.80"
           },
           {
            "value": ""
           },
           {
            "value": "-1000.00"
           },
           {
            "value": ""
           },
           {
            "value": ""
           },
           {
            "value": ""
           },
           {
            "value": ""
           },
           {
            "value": ""
           },
           {
            "value": ""
           },
           {
            "value": ""
           },
           {
            "value": ""
           },
           {
            "value": ""
           },
           {
            "value": ""
           },
           {
            "value": ""
           },
           {
            "value": ""
           },
           {
            "value": ""
           },
           {
            "value": ""
           },
           {
            "value": ""
           },
           {
            "value": ""
           },
           {
            "value": "-1754.20"
           }
          ],
          "type": "Data"
         },
         {
          "ColData": [
           {
            "value": "GST/HST Payable",
            "id": "86"
           },
           {
            "value": ""
           },
           {
            "value": "-201.47"
           },
           {
            "value": ""
           },
           {
            "value": "-177.94"
           },
           {
            "value": "455.32"
           },
           {
            "value": "-198.77"
           },
           {
            "value": "890.49"
           },
           {
            "value": "-26.00"
           },
           {
            "value": ""
           },
           {
            "value": "-284.38"
           },
           {
            "value": "58.44"
           },
           {
            "value": "-296.01"
           },
           {
            "value": "-962.00"
           },
           {
            "value": ""
           },
           {
            "value": ""
           },
           {
            "value": ""
           },
           {
            "value": "-2036.17"
           },
           {
            "value": "663.00"
           },
           {
            "value": ""
           },
           {
            "value": ""
           },
           {
            "value": ""
           },
           {
            "value": ""
           },
           {
            "value": ""
           },
           {
            "value": "-2115.49"
           }
          ],
          "type": "Data"
         },
         {
          "ColData": [
           {
            "value": "GST/HST Suspense",
            "id": "87"
           },
           {
            "value": ""
           },
           {
            "value": ""
           },
           {
            "value": ""
           },
           {
            "value": ""
           },
           {
            "value": ""
           },
           {
            "value": ""
           },
           {
            "value": ""
           },
           {
            "value": ""
           },
           {
            "value": ""
           },
           {
            "value": ""
           },
           {
            "value": ""
           },
           {
            "value": ""
           },
           {
            "value": ""
           },
           {
            "value": ""
           },
           {
            "value": ""
           },
           {
            "value": ""
           },
           {
            "value": "1836.31"
           },
           {
            "value": ""
           },
           {
            "value": ""
           },
           {
            "value": ""
           },
           {
            "value": ""
           },
           {
            "value": ""
           },
           {
            "value": ""
           },
           {
            "value": "1836.31"
           }
          ],
          "type": "Data"
         }
        ]
       },
       "Summary": {
        "ColData": [
         {
          "value": "Total Adjustments to reconcile Net Income to Net Cash provided by operations:"
         },
         {
          "value": "10259.61"
         },
         {
          "value": "-201.47"
         },
         {
          "value": "0.00"
         },
         {
          "value": "-1177.94"
         },
         {
          "value": "-7739.98"
         },
         {
          "value": "-165.44"
         },
         {
          "value": "-4548.26"
         },
         {
          "value": "9615.73"
         },
         {
          "value": "0.00"
         },
         {
          "value": "-251.05"
         },
         {
          "value": "-1338.56"
         },
         {
          "value": "-296.01"
         },
         {
          "value": "-16201.84"
         },
         {
          "value": "33.33"
         },
         {
          "value": "0.00"
         },
         {
          "value": "1356.00"
         },
         {
          "value": "-199.86"
         },
         {
          "value": "1288.04"
         },
         {
          "value": "0.00"
         },
         {
          "value": "0.00"
         },
         {
          "value": "0.00"
         },
         {
          "value": "0.00"
         },
         {
          "value": "0.00"
         },
         {
          "value": "-9567.70"
         }
        ]
       },
       "type": "Section",
       "group": "OperatingAdjustments"
      }
     ]
    },
    "Summary": {
     "ColData": [
      {
       "value": "Net cash provided by operating activities"
      },
      {
       "value": "10226.28"
      },
      {
       "value": "-1751.26"
      },
      {
       "value": "-95.00"
      },
      {
       "value": "-2546.69"
      },
      {
       "value": "-4237.50"
      },
      {
       "value": "-1727.76"
      },
      {
       "value": "-1095.00"
      },
      {
       "value": "9415.73"
      },
      {
       "value": "0.00"
      },
      {
       "value": "-2471.88"
      },
      {
       "value": "-1734.05"
      },
      {
       "value": "-2668.00"
      },
      {
       "value": "-27233.74"
      },
      {
       "value": "0.00"
      },
      {
       "value": "0.00"
      },
      {
       "value": "1356.00"
      },
      {
       "value": "-1832.23"
      },
      {
       "value": "4407.00"
      },
      {
       "value": "0.00"
      },
      {
       "value": "0.00"
      },
      {
       "value": "0.00"
      },
      {
       "value": "0.00"
      },
      {
       "value": "0.00"
      },
      {
       "value": "-21988.10"
      }
     ]
    },
    "type": "Section",
    "group": "OperatingActivities"
   },
   {
    "Header": {
     "ColData": [
      {
       "value": "FINANCING ACTIVITIES"
      },
      {
       "value": ""
      },
      {
       "value": ""
      },
      {
       "value": ""
      },
      {
       "value": ""
      },
      {
       "value": ""
      },
      {
       "value": ""
      },
      {
       "value": ""
      },
      {
       "value": ""
      },
      {
       "value": ""
      },
      {
       "value": ""
      },
      {
       "value": ""
      },
      {
       "value": ""
      },
      {
       "value": ""
      },
      {
       "value": ""
      },
      {
       "value": ""
      },
      {
       "value": ""
      },
      {
       "value": ""
      },
      {
       "value": ""
      },
      {
       "value": ""
      },
      {
       "value": ""
      },
      {
       "value": ""
      },
      {
       "value": ""
      },
      {
       "value": ""
      },
      {
       "value": ""
      }
     ]
    },
    "Rows": {
     "Row": [
      {
       "ColData": [
        {
         "value": "Note Payable",
         "id": "57"
        },
        {
         "value": ""
        },
        {
         "value": ""
        },
        {
         "value": "-376.78"
        },
        {
         "value": ""
        },
        {
         "value": ""
        },
        {
         "value": ""
        },
        {
         "value": "-376.78"
        },
        {
         "value": ""
        },
        {
         "value": ""
        },
        {
         "value": ""
        },
        {
         "value": "-376.78"
        },
        {
         "value": "-376.78"
        },
        {
         "value": ""
        },
        {
         "value": ""
        },
        {
         "value": ""
        },
        {
         "value": ""
        },
        {
         "value": "-376.78"
        },
        {
         "value": ""
        },
        {
         "value": ""
        },
        {
         "value": ""
        },
        {
         "value": ""
        },
        {
         "value": ""
        },
        {
         "value": ""
        },
        {
         "value": "-1883.90"
        }
       ],
       "type": "Data"
      },
      {
       "ColData": [
        {
         "value": "Opening Balance Equity",
         "id": "58"
        },
        {
         "value": ""
        },
        {
         "value": ""
        },
        {
         "value": ""
        },
        {
         "value": ""
        },
        {
         "value": ""
        },
        {
         "value": ""
        },
        {
         "value": ""
        },
        {
         "value": ""
        },
        {
         "value": ""
        },
        {
         "value": ""
        },
        {
         "value": ""
        },
        {
         "value": ""
        },
        {
         "value": "0.00"
        },
        {
         "value": ""
        },
        {
         "value": ""
        },
        {
         "value": ""
        },
        {
         "value": "-3668.20"
        },
        {
         "value": ""
        },
        {
         "value": ""
        },
        {
         "value": ""
        },
        {
         "value": ""
        },
        {
         "value": ""
        },
        {
         "value": ""
        },
        {
         "value": "-3668.20"
        }
       ],
       "type": "Data"
      },
      {
       "ColData": [
        {
         "value": "Owner's Equity - Draws",
         "id": "81"
        },
        {
         "value": ""
        },
        {
         "value": ""
        },
        {
         "value": ""
        },
        {
         "value": ""
        },
        {
         "value": ""
        },
        {
         "value": ""
        },
        {
         "value": ""
        },
        {
         "value": ""
        },
        {
         "value": ""
        },
        {
         "value": ""
        },
        {
         "value": "-500.00"
        },
        {
         "value": "-1000.00"
        },
        {
         "value": ""
        },
        {
         "value": ""
        },
        {
         "value": ""
        },
        {
         "value": ""
        },
        {
         "value": "-500.00"
        },
        {
         "value": ""
        },
        {
         "value": ""
        },
        {
         "value": ""
        },
        {
         "value": ""
        },
        {
         "value": ""
        },
        {
         "value": ""
        },
        {
         "value": "-2000.00"
        }
       ],
       "type": "Data"
      },
      {
       "ColData": [
        {
         "value": "Retained Earnings",
         "id": "2"
        },
        {
         "value": ""
        },
        {
         "value": ""
        },
        {
         "value": ""
        },
        {
         "value": ""
        },
        {
         "value": ""
        },
        {
         "value": ""
        },
        {
         "value": ""
        },
        {
         "value": ""
        },
        {
         "value": ""
        },
        {
         "value": ""
        },
        {
         "value": ""
        },
        {
         "value": ""
        },
        {
         "value": "9436.24"
        },
        {
         "value": ""
        },
        {
         "value": ""
        },
        {
         "value": ""
        },
        {
         "value": "3668.20"
        },
        {
         "value": ""
        },
        {
         "value": ""
        },
        {
         "value": ""
        },
        {
         "value": ""
        },
        {
         "value": ""
        },
        {
         "value": ""
        },
        {
         "value": "13104.44"
        }
       ],
       "type": "Data"
      }
     ]
    },
    "Summary": {
     "ColData": [
      {
       "value": "Net cash provided by financing activities"
      },
      {
       "value": "0.00"
      },
      {
       "value": "0.00"
      },
      {
       "value": "-376.78"
      },
      {
       "value": "0.00"
      },
      {
       "value": "0.00"
      },
      {
       "value": "0.00"
      },
      {
       "value": "-376.78"
      },
      {
       "value": "0.00"
      },
      {
       "value": "0.00"
      },
      {
       "value": "0.00"
      },
      {
       "value": "-876.78"
      },
      {
       "value": "-1376.78"
      },
      {
       "value": "9436.24"
      },
      {
       "value": "0.00"
      },
      {
       "value": "0.00"
      },
      {
       "value": "0.00"
      },
      {
       "value": "-876.78"
      },
      {
       "value": "0.00"
      },
      {
       "value": "0.00"
      },
      {
       "value": "0.00"
      },
      {
       "value": "0.00"
      },
      {
       "value": "0.00"
      },
      {
       "value": "0.00"
      },
      {
       "value": "5552.34"
      }
     ]
    },
    "type": "Section",
    "group": "FinancingActivities"
   },
   {
    "Summary": {
     "ColData": [
      {
       "value": "Net cash increase for period"
      },
      {
       "value": "10226.28"
      },
      {
       "value": "-1751.26"
      },
      {
       "value": "-471.78"
      },
      {
       "value": "-2546.69"
      },
      {
       "value": "-4237.50"
      },
      {
       "value": "-1727.76"
      },
      {
       "value": "-1471.78"
      },
      {
       "value": "9415.73"
      },
      {
       "value": "0.00"
      },
      {
       "value": "-2471.88"
      },
      {
       "value": "-2610.83"
      },
      {
       "value": "-4044.78"
      },
      {
       "value": "-17797.50"
      },
      {
       "value": "0.00"
      },
      {
       "value": "0.00"
      },
      {
       "value": "1356.00"
      },
      {
       "value": "-2709.01"
      },
      {
       "value": "4407.00"
      },
      {
       "value": "0.00"
      },
      {
       "value": "0.00"
      },
      {
       "value": "0.00"
      },
      {
       "value": "0.00"
      },
      {
       "value": "0.00"
      },
      {
       "value": "-16435.76"
      }
     ]
    },
    "type": "Section",
    "group": "CashIncrease"
   }
  ]
 }
}'''

In [46]:
data = json.loads(json_data)
data

{'Header': {'Time': '2024-06-06T05:20:45-07:00',
  'ReportName': 'CashFlow',
  'DateMacro': 'this calendar year-to-date',
  'StartPeriod': '2024-01-01',
  'EndPeriod': '2024-06-06',
  'SummarizeColumnsBy': 'Week',
  'Currency': 'CAD',
  'Option': [{'Name': 'NoReportData', 'Value': 'false'}]},
 'Columns': {'Column': [{'ColTitle': '', 'ColType': 'Account'},
   {'ColTitle': 'Jan. 1-6, 2024',
    'ColType': 'Money',
    'MetaData': [{'Name': 'StartDate', 'Value': '2024-01-01'},
     {'Name': 'EndDate', 'Value': '2024-01-06'},
     {'Name': 'ColKey', 'Value': 'Jan. 1-6, 2024'}]},
   {'ColTitle': 'Jan. 7-13, 2024',
    'ColType': 'Money',
    'MetaData': [{'Name': 'StartDate', 'Value': '2024-01-07'},
     {'Name': 'EndDate', 'Value': '2024-01-13'},
     {'Name': 'ColKey', 'Value': 'Jan. 7-13, 2024'}]},
   {'ColTitle': 'Jan. 14-20, 2024',
    'ColType': 'Money',
    'MetaData': [{'Name': 'StartDate', 'Value': '2024-01-14'},
     {'Name': 'EndDate', 'Value': '2024-01-20'},
     {'Name': 'ColKey', 'Value': 'Jan. 14-20, 2024'}]},
   {'ColTitle': 'Jan. 21-27, 2024',
    'ColType': 'Money',
    'MetaData': [{'Name': 'StartDate', 'Value': '2024-01-21'},
     {'Name': 'EndDate', 'Value': '2024-01-27'},
     {'Name': 'ColKey', 'Value': 'Jan. 21-27, 2024'}]},
   {'ColTitle': 'Jan. 28 - Feb. 3, 2024',
    'ColType': 'Money',
    'MetaData': [{'Name': 'StartDate', 'Value': '2024-01-28'},
     {'Name': 'EndDate', 'Value': '2024-02-03'},
     {'Name': 'ColKey', 'Value': 'Jan. 28 - Feb. 3, 2024'}]},
   {'ColTitle': 'Feb. 4-10, 2024',
    'ColType': 'Money',
    'MetaData': [{'Name': 'StartDate', 'Value': '2024-02-04'},
     {'Name': 'EndDate', 'Value': '2024-02-10'},
     {'Name': 'ColKey', 'Value': 'Feb. 4-10, 2024'}]},
   {'ColTitle': 'Feb. 11-17, 2024',
    'ColType': 'Money',
    'MetaData': [{'Name': 'StartDate', 'Value': '2024-02-11'},
     {'Name': 'EndDate', 'Value': '2024-02-17'},
     {'Name': 'ColKey', 'Value': 'Feb. 11-17, 2024'}]},
   {'ColTitle': 'Feb. 18-24, 2024',
    'ColType': 'Money',
    'MetaData': [{'Name': 'StartDate', 'Value': '2024-02-18'},
     {'Name': 'EndDate', 'Value': '2024-02-24'},
     {'Name': 'ColKey', 'Value': 'Feb. 18-24, 2024'}]},
   {'ColTitle': 'Feb. 25 - Mar. 2, 2024',
    'ColType': 'Money',
    'MetaData': [{'Name': 'StartDate', 'Value': '2024-02-25'},
     {'Name': 'EndDate', 'Value': '2024-03-02'},
     {'Name': 'ColKey', 'Value': 'Feb. 25 - Mar. 2, 2024'}]},
   {'ColTitle': 'Mar. 3-9, 2024',
    'ColType': 'Money',
    'MetaData': [{'Name': 'StartDate', 'Value': '2024-03-03'},
     {'Name': 'EndDate', 'Value': '2024-03-09'},
     {'Name': 'ColKey', 'Value': 'Mar. 3-9, 2024'}]},
   {'ColTitle': 'Mar. 10-16, 2024',
    'ColType': 'Money',
    'MetaData': [{'Name': 'StartDate', 'Value': '2024-03-10'},
     {'Name': 'EndDate', 'Value': '2024-03-16'},
     {'Name': 'ColKey', 'Value': 'Mar. 10-16, 2024'}]},
   {'ColTitle': 'Mar. 17-23, 2024',
    'ColType': 'Money',
    'MetaData': [{'Name': 'StartDate', 'Value': '2024-03-17'},
     {'Name': 'EndDate', 'Value': '2024-03-23'},
     {'Name': 'ColKey', 'Value': 'Mar. 17-23, 2024'}]},
   {'ColTitle': 'Mar. 24-30, 2024',
    'ColType': 'Money',
    'MetaData': [{'Name': 'StartDate', 'Value': '2024-03-24'},
     {'Name': 'EndDate', 'Value': '2024-03-30'},
     {'Name': 'ColKey', 'Value': 'Mar. 24-30, 2024'}]},
   {'ColTitle': 'Mar. 31 - Apr. 6, 2024',
    'ColType': 'Money',
    'MetaData': [{'Name': 'StartDate', 'Value': '2024-03-31'},
     {'Name': 'EndDate', 'Value': '2024-04-06'},
     {'Name': 'ColKey', 'Value': 'Mar. 31 - Apr. 6, 2024'}]},
   {'ColTitle': 'Apr. 7-13, 2024',
    'ColType': 'Money',
    'MetaData': [{'Name': 'StartDate', 'Value': '2024-04-07'},
     {'Name': 'EndDate', 'Value': '2024-04-13'},
     {'Name': 'ColKey', 'Value': 'Apr. 7-13, 2024'}]},
   {'ColTitle': 'Apr. 14-20, 2024',
    'ColType': 'Money',
    'MetaData': [{'Name': 'StartDate', 'Value': '2024-04-14'},
     {'Name': 'EndDate', 'Value': '2024-04-20'},
     {'Name': 'ColKey', 'Value': 'Apr. 14-20, 2024'}]},
   {'ColTitle': 'Apr. 21-27, 2024',
    'ColType': 'Money',
    'MetaData': [{'Name': 'StartDate', 'Value': '2024-04-21'},
     {'Name': 'EndDate', 'Value': '2024-04-27'},
     {'Name': 'ColKey', 'Value': 'Apr. 21-27, 2024'}]},
   {'ColTitle': 'Apr. 28 - May 4, 2024',
    'ColType': 'Money',
    'MetaData': [{'Name': 'StartDate', 'Value': '2024-04-28'},
     {'Name': 'EndDate', 'Value': '2024-05-04'},
     {'Name': 'ColKey', 'Value': 'Apr. 28 - May 4, 2024'}]},
   {'ColTitle': 'May 5-11, 2024',
    'ColType': 'Money',
    'MetaData': [{'Name': 'StartDate', 'Value': '2024-05-05'},
     {'Name': 'EndDate', 'Value': '2024-05-11'},
     {'Name': 'ColKey', 'Value': 'May 5-11, 2024'}]},
   {'ColTitle': 'May 12-18, 2024',
    'ColType': 'Money',
    'MetaData': [{'Name': 'StartDate', 'Value': '2024-05-12'},
     {'Name': 'EndDate', 'Value': '2024-05-18'},
     {'Name': 'ColKey', 'Value': 'May 12-18, 2024'}]},
   {'ColTitle': 'May 19-25, 2024',
    'ColType': 'Money',
    'MetaData': [{'Name': 'StartDate', 'Value': '2024-05-19'},
     {'Name': 'EndDate', 'Value': '2024-05-25'},
     {'Name': 'ColKey', 'Value': 'May 19-25, 2024'}]},
   {'ColTitle': 'May 26 - Jun. 1, 2024',
    'ColType': 'Money',
    'MetaData': [{'Name': 'StartDate', 'Value': '2024-05-26'},
     {'Name': 'EndDate', 'Value': '2024-06-01'},
     {'Name': 'ColKey', 'Value': 'May 26 - Jun. 1, 2024'}]},
   {'ColTitle': 'Jun. 2-6, 2024',
    'ColType': 'Money',
    'MetaData': [{'Name': 'StartDate', 'Value': '2024-06-02'},
     {'Name': 'EndDate', 'Value': '2024-06-06'},
     {'Name': 'ColKey', 'Value': 'Jun. 2-6, 2024'}]},
   {'ColTitle': 'Total',
    'ColType': 'Money',
    'MetaData': [{'Name': 'ColKey', 'Value': 'total'}]}]},
 'Rows': {'Row': [{'Header': {'ColData': [{'value': 'OPERATING ACTIVITIES'},
      {'value': ''},
      {'value': ''},
      {'value': ''},
      {'value': ''},
      {'value': ''},
      {'value': ''},
      {'value': ''},
      {'value': ''},
      {'value': ''},
      {'value': ''},
      {'value': ''},
      {'value': ''},
      {'value': ''},
      {'value': ''},
      {'value': ''},
      {'value': ''},
      {'value': ''},
      {'value': ''},
      {'value': ''},
      {'value': ''},
      {'value': ''},
      {'value': ''},
      {'value': ''},
      {'value': ''}]},
    'Rows': {'Row': [{'ColData': [{'value': 'Net Income'},
        {'value': '-33.33'},
        {'value': '-1549.79'},
        {'value': '-95.00'},
        {'value': '-1368.75'},
        {'value': '3502.48'},
        {'value': '-1562.32'},
        {'value': '3453.26'},
        {'value': '-200.00'},
        {'value': ''},
        {'value': '-2220.83'},
        {'value': '-395.49'},
        {'value': '-2371.99'},
        {'value': '-11031.90'},
        {'value': '-33.33'},
        {'value': ''},
        {'value': ''},
        {'value': '-1632.37'},
        {'value': '3118.96'},
        {'value': ''},
        {'value': ''},
        {'value': ''},
        {'value': ''},
        {'value': ''},
        {'value': '-12420.40'}],
       'type': 'Data',
       'group': 'NetIncome'},
      {'Header': {'ColData': [{'value': 'Adjustments to reconcile Net Income to Net Cash provided by operations:'},
         {'value': ''},
         {'value': ''},
         {'value': ''},
         {'value': ''},
         {'value': ''},
         {'value': ''},
         {'value': ''},
         {'value': ''},
         {'value': ''},
         {'value': ''},
         {'value': ''},
         {'value': ''},
         {'value': ''},
         {'value': ''},
         {'value': ''},
         {'value': ''},
         {'value': ''},
         {'value': ''},
         {'value': ''},
         {'value': ''},
         {'value': ''},
         {'value': ''},
         {'value': ''},
         {'value': '0.00'}]},
       'Rows': {'Row': [{'ColData': [{'value': 'Accounts Receivable',
            'id': '32'},
           {'value': '10226.28'},
           {'value': ''},
           {'value': ''},
           {'value': ''},
           {'value': '-8441.10'},
           {'value': ''},
           {'value': '-8249.00'},
           {'value': '9415.73'},
           {'value': ''},
           {'value': ''},
           {'value': '-2147.00'},
           {'value': ''},
           {'value': '-9435.50'},
           {'value': ''},
           {'value': ''},
           {'value': '1356.00'},
           {'value': ''},
           {'value': '-1356.00'},
           {'value': ''},
           {'value': ''},
           {'value': ''},
           {'value': ''},
           {'value': ''},
           {'value': '-8630.59'}],
          'type': 'Data'},
         {'ColData': [{'value': 'Inventory Asset', 'id': '85'},
           {'value': ''},
           {'value': ''},
           {'value': ''},
           {'value': ''},
           {'value': ''},
           {'value': ''},
           {'value': '3301.74'},
           {'value': ''},
           {'value': ''},
           {'value': ''},
           {'value': '750.00'},
           {'value': ''},
           {'value': '-5804.34'},
           {'value': ''},
           {'value': ''},
           {'value': ''},
           {'value': ''},
           {'value': '1981.04'},
           {'value': ''},
           {'value': ''},
           {'value': ''},
           {'value': ''},
           {'value': ''},
           {'value': '228.44'}],
          'type': 'Data'},
         {'ColData': [{'value': 'Accumulated Depreciation', 'id': '33'},
           {'value': '33.33'},
           {'value': ''},
           {'value': ''},
           {'value': ''},
           {'value': ''},
           {'value': '33.33'},
           {'value': ''},
           {'value': ''},
           {'value': ''},
           {'value': '33.33'},
           {'value': ''},
           {'value': ''},
           {'value': ''},
           {'value': '33.33'},
           {'value': ''},
           {'value': ''},
           {'value': ''},
           {'value': ''},
           {'value': ''},
           {'value': ''},
           {'value': ''},
           {'value': ''},
           {'value': ''},
           {'value': '133.32'}],
          'type': 'Data'},
         {'ColData': [{'value': 'Accounts Payable', 'id': '31'},
           {'value': ''},
           {'value': ''},
           {'value': ''},
           {'value': ''},
           {'value': ''},
           {'value': ''},
           {'value': '508.51'},
           {'value': '226.00'},
           {'value': ''},
           {'value': ''},
           {'value': ''},
           {'value': ''},
           {'value': ''},
           {'value': ''},
           {'value': ''},
           {'value': ''},
           {'value': ''},
           {'value': ''},
           {'value': ''},
           {'value': ''},
           {'value': ''},
           {'value': ''},
           {'value': ''},
           {'value': '734.51'}],
          'type': 'Data'},
         {'ColData': [{'value': 'Visa Credit Card', 'id': '79'},
           {'value': ''},
           {'value': ''},
           {'value': ''},
           {'value': '-1000.00'},
           {'value': '245.80'},
           {'value': ''},
           {'value': '-1000.00'},
           {'value': ''},
           {'value': ''},
           {'value': ''},
           {'value': ''},
           {'value': ''},
           {'value': ''},
           {'value': ''},
           {'value': ''},
           {'value': ''},
           {'value': ''},
           {'value': ''},
           {'value': ''},
           {'value': ''},
           {'value': ''},
           {'value': ''},
           {'value': ''},
           {'value': '-1754.20'}],
          'type': 'Data'},
         {'ColData': [{'value': 'GST/HST Payable', 'id': '86'},
           {'value': ''},
           {'value': '-201.47'},
           {'value': ''},
           {'value': '-177.94'},
           {'value': '455.32'},
           {'value': '-198.77'},
           {'value': '890.49'},
           {'value': '-26.00'},
           {'value': ''},
           {'value': '-284.38'},
           {'value': '58.44'},
           {'value': '-296.01'},
           {'value': '-962.00'},
           {'value': ''},
           {'value': ''},
           {'value': ''},
           {'value': '-2036.17'},
           {'value': '663.00'},
           {'value': ''},
           {'value': ''},
           {'value': ''},
           {'value': ''},
           {'value': ''},
           {'value': '-2115.49'}],
          'type': 'Data'},
         {'ColData': [{'value': 'GST/HST Suspense', 'id': '87'},
           {'value': ''},
           {'value': ''},
           {'value': ''},
           {'value': ''},
           {'value': ''},
           {'value': ''},
           {'value': ''},
           {'value': ''},
           {'value': ''},
           {'value': ''},
           {'value': ''},
           {'value': ''},
           {'value': ''},
           {'value': ''},
           {'value': ''},
           {'value': ''},
           {'value': '1836.31'},
           {'value': ''},
           {'value': ''},
           {'value': ''},
           {'value': ''},
           {'value': ''},
           {'value': ''},
           {'value': '1836.31'}],
          'type': 'Data'}]},
       'Summary': {'ColData': [{'value': 'Total Adjustments to reconcile Net Income to Net Cash provided by operations:'},
         {'value': '10259.61'},
         {'value': '-201.47'},
         {'value': '0.00'},
         {'value': '-1177.94'},
         {'value': '-7739.98'},
         {'value': '-165.44'},
         {'value': '-4548.26'},
         {'value': '9615.73'},
         {'value': '0.00'},
         {'value': '-251.05'},
         {'value': '-1338.56'},
         {'value': '-296.01'},
         {'value': '-16201.84'},
         {'value': '33.33'},
         {'value': '0.00'},
         {'value': '1356.00'},
         {'value': '-199.86'},
         {'value': '1288.04'},
         {'value': '0.00'},
         {'value': '0.00'},
         {'value': '0.00'},
         {'value': '0.00'},
         {'value': '0.00'},
         {'value': '-9567.70'}]},
       'type': 'Section',
       'group': 'OperatingAdjustments'}]},
    'Summary': {'ColData': [{'value': 'Net cash provided by operating activities'},
      {'value': '10226.28'},
      {'value': '-1751.26'},
      {'value': '-95.00'},
      {'value': '-2546.69'},
      {'value': '-4237.50'},
      {'value': '-1727.76'},
      {'value': '-1095.00'},
      {'value': '9415.73'},
      {'value': '0.00'},
      {'value': '-2471.88'},
      {'value': '-1734.05'},
      {'value': '-2668.00'},
      {'value': '-27233.74'},
      {'value': '0.00'},
      {'value': '0.00'},
      {'value': '1356.00'},
      {'value': '-1832.23'},
      {'value': '4407.00'},
      {'value': '0.00'},
      {'value': '0.00'},
      {'value': '0.00'},
      {'value': '0.00'},
      {'value': '0.00'},
      {'value': '-21988.10'}]},
    'type': 'Section',
    'group': 'OperatingActivities'},
   {'Header': {'ColData': [{'value': 'FINANCING ACTIVITIES'},
      {'value': ''},
      {'value': ''},
      {'value': ''},
      {'value': ''},
      {'value': ''},
      {'value': ''},
      {'value': ''},
      {'value': ''},
      {'value': ''},
      {'value': ''},
      {'value': ''},
      {'value': ''},
      {'value': ''},
      {'value': ''},
      {'value': ''},
      {'value': ''},
      {'value': ''},
      {'value': ''},
      {'value': ''},
      {'value': ''},
      {'value': ''},
      {'value': ''},
      {'value': ''},
      {'value': ''}]},
    'Rows': {'Row': [{'ColData': [{'value': 'Note Payable', 'id': '57'},
        {'value': ''},
        {'value': ''},
        {'value': '-376.78'},
        {'value': ''},
        {'value': ''},
        {'value': ''},
        {'value': '-376.78'},
        {'value': ''},
        {'value': ''},
        {'value': ''},
        {'value': '-376.78'},
        {'value': '-376.78'},
        {'value': ''},
        {'value': ''},
        {'value': ''},
        {'value': ''},
        {'value': '-376.78'},
        {'value': ''},
        {'value': ''},
        {'value': ''},
        {'value': ''},
        {'value': ''},
        {'value': ''},
        {'value': '-1883.90'}],
       'type': 'Data'},
      {'ColData': [{'value': 'Opening Balance Equity', 'id': '58'},
        {'value': ''},
        {'value': ''},
        {'value': ''},
        {'value': ''},
        {'value': ''},
        {'value': ''},
        {'value': ''},
        {'value': ''},
        {'value': ''},
        {'value': ''},
        {'value': ''},
        {'value': ''},
        {'value': '0.00'},
        {'value': ''},
        {'value': ''},
        {'value': ''},
        {'value': '-3668.20'},
        {'value': ''},
        {'value': ''},
        {'value': ''},
        {'value': ''},
        {'value': ''},
        {'value': ''},
        {'value': '-3668.20'}],
       'type': 'Data'},
      {'ColData': [{'value': "Owner's Equity - Draws", 'id': '81'},
        {'value': ''},
        {'value': ''},
        {'value': ''},
        {'value': ''},
        {'value': ''},
        {'value': ''},
        {'value': ''},
        {'value': ''},
        {'value': ''},
        {'value': ''},
        {'value': '-500.00'},
        {'value': '-1000.00'},
        {'value': ''},
        {'value': ''},
        {'value': ''},
        {'value': ''},
        {'value': '-500.00'},
        {'value': ''},
        {'value': ''},
        {'value': ''},
        {'value': ''},
        {'value': ''},
        {'value': ''},
        {'value': '-2000.00'}],
       'type': 'Data'},
      {'ColData': [{'value': 'Retained Earnings', 'id': '2'},
        {'value': ''},
        {'value': ''},
        {'value': ''},
        {'value': ''},
        {'value': ''},
        {'value': ''},
        {'value': ''},
        {'value': ''},
        {'value': ''},
        {'value': ''},
        {'value': ''},
        {'value': ''},
        {'value': '9436.24'},
        {'value': ''},
        {'value': ''},
        {'value': ''},
        {'value': '3668.20'},
        {'value': ''},
        {'value': ''},
        {'value': ''},
        {'value': ''},
        {'value': ''},
        {'value': ''},
        {'value': '13104.44'}],
       'type': 'Data'}]},
    'Summary': {'ColData': [{'value': 'Net cash provided by financing activities'},
      {'value': '0.00'},
      {'value': '0.00'},
      {'value': '-376.78'},
      {'value': '0.00'},
      {'value': '0.00'},
      {'value': '0.00'},
      {'value': '-376.78'},
      {'value': '0.00'},
      {'value': '0.00'},
      {'value': '0.00'},
      {'value': '-876.78'},
      {'value': '-1376.78'},
      {'value': '9436.24'},
      {'value': '0.00'},
      {'value': '0.00'},
      {'value': '0.00'},
      {'value': '-876.78'},
      {'value': '0.00'},
      {'value': '0.00'},
      {'value': '0.00'},
      {'value': '0.00'},
      {'value': '0.00'},
      {'value': '0.00'},
      {'value': '5552.34'}]},
    'type': 'Section',
    'group': 'FinancingActivities'},
   {'Summary': {'ColData': [{'value': 'Net cash increase for period'},
      {'value': '10226.28'},
      {'value': '-1751.26'},
      {'value': '-471.78'},
      {'value': '-2546.69'},
      {'value': '-4237.50'},
      {'value': '-1727.76'},
      {'value': '-1471.78'},
      {'value': '9415.73'},
      {'value': '0.00'},
      {'value': '-2471.88'},
      {'value': '-2610.83'},
      {'value': '-4044.78'},
      {'value': '-17797.50'},
      {'value': '0.00'},
      {'value': '0.00'},
      {'value': '1356.00'},
      {'value': '-2709.01'},
      {'value': '4407.00'},
      {'value': '0.00'},
      {'value': '0.00'},
      {'value': '0.00'},
      {'value': '0.00'},
      {'value': '0.00'},
      {'value': '-16435.76'}]},
    'type': 'Section',
    'group': 'CashIncrease'}]}}

In [47]:
column_titles = [col['ColTitle'] for col in data['Columns']['Column']]

In [49]:
columns_data = []
for column in data['Columns']['Column']:
    columns_data.append(column.get('ColTitle', ''))

In [50]:
rows_data = []
for row in data['Rows']['Row']:
    row_data = [cell['value'] for cell in row['Summary']['ColData']]
    rows_data.append(row_data)

['Net cash increase for period',
 '10226.28',
 '-1751.26',
 '-471.78',
 '-2546.69',
 '-4237.50',
 '-1727.76',
 '-1471.78',
 '9415.73',
 '0.00',
 '-2471.88',
 '-2610.83',
 '-4044.78',
 '-17797.50',
 '0.00',
 '0.00',
 '1356.00',
 '-2709.01',
 '4407.00',
 '0.00',
 '0.00',
 '0.00',
 '0.00',
 '0.00',
 '-16435.76']

In [51]:
df = pd.DataFrame(rows_data, columns=columns_data)
df

,,"Jan. 1-6, 2024","Jan. 7-13, 2024","Jan. 14-20, 2024","Jan. 21-27, 2024","Jan. 28 - Feb. 3, 2024","Feb. 4-10, 2024","Feb. 11-17, 2024","Feb. 18-24, 2024","Feb. 25 - Mar. 2, 2024",...,"Apr. 7-13, 2024","Apr. 14-20, 2024","Apr. 21-27, 2024","Apr. 28 - May 4, 2024","May 5-11, 2024","May 12-18, 2024","May 19-25, 2024","May 26 - Jun. 1, 2024","Jun. 2-6, 2024",Total
0,Net cash provided by operating activities,10226.28,-1751.26,-95.00,-2546.69,-4237.50,-1727.76,-1095.00,9415.73,0.00,...,0.00,1356.00,-1832.23,4407.00,0.00,0.00,0.00,0.00,0.00,-21988.10
1,Net cash provided by financing activities,0.00,0.00,-376.78,0.00,0.00,0.00,-376.78,0.00,0.00,...,0.00,0.00,-876.78,0.00,0.00,0.00,0.00,0.00,0.00,5552.34
2,Net cash increase for period,10226.28,-1751.26,-471.78,-2546.69,-4237.50,-1727.76,-1471.78,9415.73,0.00,...,0.00,1356.00,-2709.01,4407.00,0.00,0.00,0.00,0.00,0.00,-16435.76